### ISSUE TITLE
app running, but no connection to go-e-charger 

### ISSUE THREAD

**Issue by WLBI** [RoodyCode/go-e-Charger-web-app#1]
I tried to install it and it looks like it worked. 
$ npm run preview

> go-e-charger@0.0.0 preview
> vite preview --host

  ➜  Local:   http://localhost:4173/
  ➜  Network: http://192.168.178.20:4173/

Perfect.. But when I open the website "http://192.168.178.20:4173/" in the browser, there is no connection to the go-e-charger. 
![grafik](https://github.com/RoodyCode/go-e-Charger-Web-App/assets/12268716/ba0b82a6-1b31-454b-a3eb-f4d8da183824)

I also can't see any place, where I can enter the hostname or ip-address of the go-e-charger.
In my wifi router the go-e-charger have the connection:
hostname: go-echarger-123456 (number changed)
ip-address: 192.168.178.29

any help?

**Comment by RoodyCode** [comment]
Hey, you can configure the IP in the following file:
`src/config.js`
