### ISSUE TITLE
Error while npm build 

### ISSUE THREAD

**Issue by bbsoosi** [RoodyCode/go-e-Charger-web-app#2]
I tried out to build the project. 
I have installed node 12.22.9,  npm 8.5.1
I got an error on npm run build:

$ npm run preview

> go-e-charger@0.0.0 preview
> vite preview --host

file:///go-e-Charger-Web-App/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/

Thank you.

**Comment by RoodyCode** [comment]
Hi there,

Try upgrading your Node.js to at least version 14.x.x or higher.

**Comment by bbsoosi** [comment]
works now, thanks :+1:
